services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8003

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: pwd
      # MARIADB_DATABASE: bot_or_not_db
      # MARIADB_USER: myuser
      # MARIADB_PASSWORD: pwd
    ports:
      - "3307:3306"
    container_name: database
    volumes:
      - ./mariadb_init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppwd"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s

volumes:
  mariadb_data:
